kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-1.32.0
featureGates:
  "MutatingAdmissionPolicy": true
  "PodLogsQuerySplitStreams": true
  # 上記の"PodLogsQuerySplitStreams"はkepだと"SplitStdoutAndStderr"と書いてあるため、注意が必要
  "PodLevelResources": true
  "PodLifecycleSleepActionAllowZero": true
  "ComponentFlagz": true
  "ComponentStatusz": true
runtimeConfig:
  api/alpha: "true"

nodes:
- role: control-plane
  image: kindest/node:v1.32.0
- role: worker
  image: kindest/node:v1.32.0
- role: worker
  image: kindest/node:v1.32.0
